url: "https://www.kyletress.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kyletress.com" # the name of your site, e.g. ACME Corp.
